name: Update Hosts File

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 1 * *"

jobs:
  build-hosts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: setup git config
      run: |
        git config user.name "r-neuschulz"
        git config user.email "r-neuschulz@protonmail.com"
    - name: Pull latest changes
      run: |
        git pull origin main
    - name: Fetch StevenBlack's social hosts file
      run: |
        curl -o social_hosts https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social-only/hosts
    - name: Amend social_hosts to hosts file
      run: |
        sed -i '/^# Updated:/ r social_hosts' hosts
    - name: Commit and Push Changes
      run: |
        git add hosts
        git commit -m "💻 Automatic Update of hosts File"
        git push origin main
