name: Update Hosts File

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build-hosts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: setup git config
      run: |
        git config user.name "r-neuschulz"
        git config user.email "r-neuschulz@protonmail.com"
    - name: Pull latest changes
      run: |
        git pull origin main
    - name: Fetch StevenBlacks hosts file
      run: |
        curl -o hosts https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    - name: Fetch StevenBlacks social_hosts file
      run: |
        curl -o social_hosts https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social-only/hosts
    - name: Amend social_hosts to hosts file
      run: |
        sed -i '/^# Updated:/ r social_hosts' hosts
    - name: Whitelist Telegram, LinkedIn and WhatsApp
      run: |
        sed -i -e '/# WhatsApp/,/#/ { /# WhatsApp/! { /#/! d } }' -e '/# Telegram/,/#/ { /# Telegram/! { /#/! d } }' -e '/# LinkedIn/,/#/ { /# LinkedIn/! { /#/! d } }' hosts
    - name: Amend manual_hosts to hosts file
      run: |
        cat manual_hosts >> hosts
    - name: Check for invalid lines in hosts file
      run: |
        invalid_lines=$(grep -Ev '^(#\s|0\.0\.0\.0\s)' hosts | wc -l)
        echo "Number of invalid lines: $invalid_lines"
    - name: Delete invalid lines in hosts file
      run: |
        sed -i '/^\(# \|0\.0\.0\.0 \)/!d' hosts
    - name: Delete unneded file(s)
      run: |
        rm -rf social_hosts
    - name: Commit and Push Changes if Needed
      run: |
        if ! git diff --quiet; then
          git add hosts
          git commit -m "💻 Automatic Update of hosts File"
          git push origin main --force
        else
          echo "No changes to commit"
        fi
